name: kerja_praktik_app
description: CateTaja - Smart expense and income tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  flutter_riverpod: ^3.2.1
  shared_preferences: ^2.5.4
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "logo/app.png"
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "logo/app.png"

flutter:
  uses-material-design: true

  assets:
    - logo/app.png

  # To add custom fonts to your application, add a fonts section here:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
